# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Bundle

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload build files
      uses: actions/upload-artifact@v2
      with:
        name: build-files
        path: build/*
    - name: Upload dist files
      uses: actions/upload-artifact@v2
      with:
        name: dist-files
        path: dist/*
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: mParticle Automation
        author_email: developers@mparticle.com
        message: "Generate latest bundle"
        force: true
        add: "dist/ build/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
